name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_URL = "https://evident-feline-33888.upstash.io"
UPSTASH_REDIS_TOKEN = "AYRgAAIncDE5NjYxZDE2YTRkMDk0OGIwOWZjZGE2OGEyNzk1ZjFkOXAxMzM4ODg"